# Generated by Django 4.2.16 on 2024-11-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="leave_deducted",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
