# Generated by Django 4.2.16 on 2024-11-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_attendancerecord_leave_deducted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="annual_leave_balance",
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
    ]
